platform: linux

image_resource:
  type: registry-image
  source:
    aws_access_key_id: ((ecr_aws_key))
    aws_secret_access_key: ((ecr_aws_secret))
    repository: general-task
    aws_region: us-gov-west-1
    tag: latest

inputs:
- name: shibboleth-config
- name: common
- name: terraform-yaml

outputs:
- name: shibboleth-manifest

run:
  path: sh
  args:
  - -exc
  - |
    shibboleth-config/generate-deployment-manifest.sh \
      common/secrets.yml \
      > shibboleth-manifest/manifest.yml
